Задачи на проверку
js-tasks-ru/vue-20230120_mitya-mf pull request #2
Opened 2023-01-25 21:31 UTC by mityamf

Выполнены задачи 01/01...04

2023-01-25 21:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-25 23:11 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` требуется двустороннее связывание полей ввода.

Задача `01-basics/03-MarkedList` не решена. По условию требуется выделить классом элементы, попадающие под условие выделения.

2023-01-25 23:11 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      <button type="button" @click="increment">{{counter}}</button>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ counter }}`

2023-01-25 23:11 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>          </div>
Без использования `v-model` или привязки `value` получается односторонне связывание. Это поле ввода позволяет вводить числа, но его значение не определяется состоянием приложения. При изменении состояния в инпуте останется старое значение.

2023-01-25 23:11 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +
К `number` можно не приводить. Vue сам это сделает под капотом для поля ввода с `type="number"`

2023-01-25 23:11 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
>          </ul>
email-ы отфильтрованы, а не промаркированы. Задача не такая же, как была на вебинаре...

2023-01-26 16:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-26 16:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-26 16:56 UTC, mityamf commented on 01-basics/02-VueCalculator/index.html
>          </div>
это было сделано намеренно, т.к. я полагаю, что функционал калькулятора предполагает именно одностороннее связывание. Исправил в новом PR

2023-01-26 16:59 UTC, mityamf commented on 01-basics/02-VueCalculator/script.js
> +
как оказалось, не всегда. Если данные пробрасываются через `v-on:input` (как было в моем прошлом решении), то это оказывается строка и при операции сложения происходит конкатенация

2023-01-26 17:31 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +
Да, это фича именно использования `v-model`. Не обратил на это внимание при проверке.

2023-01-26 17:55 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>          </div>
Двустороннее связывание нужно, чтобы состояние страницы всегда соответствовало и определялось состоянием приложения. Даже если в какой-то момент числа никак не меняются вне этих полей ввода, позже может появиться новая функциональность. Vue позволяет работать отталкиваясь по возможности всегда именно от данных, не думая о том, может ли тут быть другое место использования или изменения данных.

2023-01-26 17:55 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-01-26 17:56 UTC, merged