Задачи на проверку 02/01...06
js-tasks-ru/vue-20230120_mitya-mf pull request #3
Opened 2023-01-30 21:19 UTC by mityamf

В финальной задаче не разобрался со статусами и запутался, где получать данные по API, поэтому подсмотрел решение. Как оказалось, думал в верном направлении.

2023-01-30 21:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-01 04:22 UTC, ShGKme requested changes
В `02-components/01-CounterButtonComponent` требуется поправить решение таким образом, чтобы в нём не мутировались напрямую DOM элементы. Желательно также не работать с `value` у кнопки. 

Остальные задачи приняты.

2023-02-01 04:22 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +            {{ count }}</button>`,
У полей ввода мы работали с свойством `value`, так именно этим свойством определяется значение поля ввода, и из него же можно получить значение после ввода пользователем. Но кнопке за очень редким исключением не нужно значение, не нужно `value`. 

Привязка значения `:value="count"` - лишнее действие. Оно не создаёт никаких проблем, но важно понимание, что это не что-то необходимое для решения или работы с событиями во Vue.

А вот `++$event.target.value` - это действие, которое делать нельзя. Этим действием после клика по кнопке вы напрямую изменяете свойства DOM элемента, который должен определяться шаблоном Vue. 

Во Vue кроме особых случаев нельзя вручную мутировать DOM дерево, за которое отвечает Vue. Этот DOM рендерится в соответствии с шаблоном и состоянием приложения. Мы можем только менять данные приложения.

Для передачи с событием значения на 1 больше текущего счётчика не требуется менять свойства DOM элементов. Нужно только вычислить и передать в аргумент функции значение на 1 больше.

2023-02-13 18:37 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-13 19:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-14 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-14 19:29 UTC, ShGKme requested changes
В `04-vue-cli/01-UiFormGroup1` требуется использовать объектный синтаксис привязки класса по условию, чтобы лишний раз с ним попрактиковаться. Это очень часто-используемая возможность во Vue.

Все остальные задачи и исправления приняты.

2023-02-14 19:29 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    }
Это не приводит к ошибкам, но переопределять значение аргументов функции считается плохой практикой.
Подробнее: [https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/](https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/)

И в этой функции это изменение даже не используется, значение `value` после увеличения нигде не используется в методе. Можно просто передать `value + 1`, не меняя аргумент `value`.

2023-02-14 19:29 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  }
Первый фон с `linear-gradient` можно оставить в стилях первым обычным фоном, а уже второй привязывать с `v-bind`, чтобы выражение было проще, и не было дублирования довольно сложного значения, не нужно было его потом менять в двух местах.

2023-02-14 19:29 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
>      <!-- form-group_inline -->
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выраженю требуется добавлять. И не нужно делать тернарников с пустым else.

[https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects](https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects)

2023-02-15 19:08 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-15 20:28 UTC, ShGKme requested changes
В `04-vue-cli/02-TheToaster` требуется либо полностью оставить стилизацию разных тостов в компоненте родителе (в нём же хранить классы, стили), либо полностью перенести в `UiToast`. Сейчас при использовании компонента `UiToast` разработчик должен вешать на него класс, стили для которого описаны внутри компонента и работают за счёт протекания scoped стилей.

Остальные задачи приняты

2023-02-15 20:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      })
`UiToast` компонент сам отвечает за вывод одного тоста. Именно в нём описаны классы   `toast_success` и `toast_error`. В этом случае лучше либо ему же определять, какие классы и иконки должны быть у разных типов тостов, либо вообще ничего не знать про разные типы тостов. Тогда и стилизацией этих тостов должен заниматься родитель.

Сейчас об этом должен знать пользователь компонента, который должен передать правильное имя класса из исходного кода компонента.

2023-02-16 00:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-16 00:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-16 21:56 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-17 14:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-17 15:45 UTC, ShGKme requested changes
Всё ещё осталась проблема с разделением стилей между `UiToast` и `TheToaster`.

При декомпозиции компонента на части и в целом при разработке компонента желательно делать его самостоятельным - переиспользуемым и независимым блоком приложения. Так, чтобы он работал не только в том единственном месте, где он используется сейчас, но и при его использовании в другом месте. Аналогично блок в БЭМ верстается так, чтобы его можно было вставить и в другое место.

Это не всегда просто, не всегда необходимо, не всегда имеет смысл и может не стоить затраченных усилий. Но сейчас выделить полностью самостоятельный `UiToast` очень просто. В тоже время текущее решение работает неявно, из-за особенностей scoped стилей в Vue.

2023-02-17 15:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</template>
Теперь компонент использует класс `toast`, стили для которого отсутствуют в компоненте и тоже работают только за счёт протекания в частном случае в родителе `TheToaster`.

2023-02-24 21:02 UTC, mityamf commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</template>
А стили можно переписать иначе? 
Без этого не понятно, как быть с селекторами ``.toast.toast_success`` / ``.toast.toast_error``, которые с одной стороны определяют стиль того или иного тоста (и по этой логике, должны лежать в компоненте ``UiToast``), а с другой стороны они же устанавливаются родительским компонентом и по этой логике должны находиться в нем.

2023-02-24 23:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-25 21:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-25 22:16 UTC, ShGKme requested changes
В `04-vue-cli/03-UiDropdown1` требуется избавиться от побочных эффектов в вычисляемом свойстве. Остальные задачи приняты.

2023-02-25 22:16 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Вычисляемое свойство ни в коем случае не должно иметь побочных эффектов в своём вычислении. Только вычислять и возвращать значение свойства.

2023-02-25 22:16 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`selected` - не самостоятельное свойства, у него нет собственного независимого значения. Его значение всегда является результатом вычисления на основе `modelValue` и `options`.

2023-02-25 22:16 UTC, ShGKme commented on 05-vue-router/01-AuthPages/components/MeetupsNav.vue
>  };
Уточню, что этот метод не нужен для работы компонента. Он был на вебинаре в процессе изучения роутинга, когда мы ещё не узнали про `<RouterLink>`

2023-02-25 22:16 UTC, ShGKme commented on 05-vue-router/01-AuthPages/components/MeetupsNav.vue
> +    <RouterLink :to="'/register'" class="nav__link" >Регистрация</RouterLink>
Если значение параметра - константная строка, можно не испльзовать привязку к js выражению:
`:to="'/login'"` - `to="/login"`

2023-02-25 22:16 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +    }
Если в переменной `savedPosition` есть значение, то функция завершится ещё на 7-ой строке. В 15-ой строке всегда возвращается `undefined`. Это не приводит к некорретной работе, здесь и нужно возвращать `falsy` значение. Но возврат значения получается неявный - вместо явно falsy (false/undefined) значения возвращается переменная, в которой в этом месте так получилось, что может быть только `undefined`.

2023-02-25 22:16 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</template>
Да, если здесь выносить стили тостов разных типов из компонента тоста, то селектор у родителя должен быть просто `.toast_error` и `.toast_success`.

2023-02-26 12:32 UTC, mityamf commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
согласен, но оно у меня используется в двух местах. Не хотелось бы вычислять его дважды, если можно один раз посчитать значение ``selected``
Почему я не могу иметь некую глобальную переменную для компонента, даже если она является лишь результатом вычисления на основе modelValue и options?

2023-02-26 12:37 UTC, mityamf commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
или надо просто сделать ``selected`` computed?

2023-02-26 18:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-26 19:55 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Да, или сделать `selectedOption` возвращающим целиком `option`, а не текст.

2023-03-01 21:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-03-10 20:44 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-03-10 20:47 UTC, merged